import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Design System "Summer Joy & Inclusivity"
        primary: '#b90040',
        'on-primary': '#ffffff',
        'primary-container': '#e31754',
        'on-primary-container': '#fffbff',
        'primary-fixed': '#ffd9dc',
        'primary-fixed-dim': '#ffb2ba',
        'on-primary-fixed': '#400011',
        'on-primary-fixed-variant': '#910030',
        'inverse-primary': '#ffb2ba',
        secondary: '#006b5f',
        'on-secondary': '#ffffff',
        'secondary-container': '#76f4e0',
        'on-secondary-container': '#006f63',
        tertiary: '#974400',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#bb580d',
        'on-tertiary-container': '#fffbff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        surface: '#fff8f7',
        'surface-dim': '#f2d3d5',
        'surface-bright': '#fff8f7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fff0f0',
        'surface-container': '#ffe9ea',
        'surface-container-high': '#ffe1e3',
        'surface-container-highest': '#fbdbdd',
        'on-surface': '#281719',
        'on-surface-variant': '#5c3f42',
        'surface-variant': '#fbdbdd',
        'surface-tint': '#bd0042',
        'inverse-surface': '#3f2b2d',
        'inverse-on-surface': '#ffeced',
        outline: '#906f72',
        'outline-variant': '#e5bdc0',
        background: '#fff8f7',
        'on-background': '#281719',
      },
      borderRadius: {
        sm: '0.5rem',
        DEFAULT: '1rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        base: '8px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        'margin-mobile': '16px',
        'margin-desktop': '80px',
        gutter: '24px',
      },
      fontFamily: {
        sans: ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '900' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '900' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
} satisfies Config;